### ISSUE TITLE
Queries Browser: Better order for query types?

### ISSUE THREAD

**Issue by ClotildeToullec** [moosetechnology/MooseIDE#1005]
When creating a new query, the first droplist (type of query) is sorted alphabetically.
It is a bit confusing because:
- Unary queries are mixed with more complex ones
- The position of a certain type is not at the same place depending in the number of queries available (if we can create a N-Ary query or not).

We could order queries by Unary / Complement / N-Ary, and then alphabetically in each category.

**Comment by NicolasAnquetil** [comment]
yes
