### ISSUE TITLE
Architectural: Open nodes on double click?

### ISSUE THREAD

**Issue by jecisc** [moosetechnology/MooseIDE#1018]
It would be nice to be able to open nodes in the architectural using a double click instead of having to use the contextual menu.

What do you think?

**Comment by anneetien** [comment]
Oh yes!
But perhaps not instead, but also :-)

Anne

**Comment by jecisc** [comment]
This is what I had in mind yes! :)

**Comment by NicolasAnquetil** [comment]
The action on DoubleClick should be configurable

For example I would like it to be Propagate

**Comment by LABSARI** [comment]
Fixed by #1081
