### ISSUE TITLE
QueryBrowser: Add tag in in Type Query

### ISSUE THREAD

**Issue by NicolasAnquetil** [moosetechnology/MooseIDE#104]

**Comment by jordanmontt** [comment]
We should add the tag field for the types of FQTypeQuery

**Comment by jordanmontt** [comment]
![image](https://user-images.githubusercontent.com/33934979/120374935-b42e7e80-c309-11eb-98e8-7c03923dce30.png)
These are the currents types

**Comment by jordanmontt** [comment]
I don't undestant this @NicolasAnquetil

**Comment by NicolasAnquetil** [comment]
Current state of analysis:

- FamixTag should use TEntityMetaLevelDependency
  - we could redefine FamixTag class >> #privateChildrenSelectorsIn: aMetamodel 	^ #( taggedEntities )	
  - we could redefine FamixTag class >> #privateChildrenTypesIn: aMetamodel	^{ MooseEntity }
- FamixTag should use FamixTNamedEntity
  - remove slot #name
  - remove methods inplemented in FamixTNamedEntity

- FamixTag >> #description should be renamed to not override MooseEntity >> #description

**Comment by NicolasAnquetil** [comment]
after a bit more study, things are a bit more complicated because there are also "Virtual tags" (tag in intent)

So maybe a solution would be to just have a special query that returns all the tags

But anyway, having TEntityMetaLevelDependency (and FamixTNamedEntity) on tags would certainly be needed for other things in Moose, so this is something to keep

**Comment by NicolasAnquetil** [comment]
created to issues in Famix for tags linked to this:
- https://github.com/moosetechnology/Famix/issues/418
- https://github.com/moosetechnology/Famix/issues/419

**Comment by NicolasAnquetil** [comment]
migrating discussion to #291
