### ISSUE TITLE
Architectural map: use a checkbox list when selecting a list of element in settings

### ISSUE THREAD

**Issue by LABSARI** [moosetechnology/MooseIDE#1042]
![image](https://github.com/moosetechnology/MooseIDE/assets/75275113/095e0797-1c06-41ca-a41d-8a069b050f5e)
Above is the current selection list, it is not clear what is selected or not and user is not aware that they can select multiple items in the tag list. It should be like the option "links to show" of architectural map: 
![Screenshot 2024-02-29 at 16 06 45](https://github.com/moosetechnology/MooseIDE/assets/75275113/1bd85b49-393a-48c7-a945-ada009a84ebe)

**Comment by NicolasAnquetil** [comment]
note: the same thing has already been implemented for DistributionMap #965
