### ISSUE TITLE
ArchitecturalMap should have links by default

### ISSUE THREAD

**Issue by NicolasAnquetil** [moosetechnology/MooseIDE#1073]
Currently the map appears without any link
This can be confusing
I propose to show inheritance and invocation links by default

**Comment by badetitou** [comment]
I agree with the idea of adding default relationship. Invocation and inheritance seems ok. 
My fear is that sometimes invocations + inheritance create a messy vizu whereas with only inheritance it is often more clear?

**Comment by NicolasAnquetil** [comment]
- It is not always used with classes: I just used it to understand the interactions between (50) methods in a class
- Inheritance and Invocation seem to be the most used relationship
- It would still be configurable from the settings
