### ISSUE TITLE
The payground is no longer a moose playground in P12

### ISSUE THREAD

**Issue by ClotildeToullec** [moosetechnology/MooseIDE#1111]
and it should be.

**Comment by guillep** [comment]
@ClotildeToullec we took the latest Pharo12 and we downloaded mooseIDE on top of it, and the playground menu and shortcut are bound to the moose playground. Maybe it was fixed in the meantime?

I propose this is closed :)

**Comment by ClotildeToullec** [comment]
The problem seems to be in the image generated by CI
