### ISSUE TITLE
Logger browser does not show a scrollbar when has several buses 

### ISSUE THREAD

**Issue by jordanmontt** [moosetechnology/MooseIDE#112]
If you have, for example, 5 buses,  the logger does not show a scroll bar so you cannot see all buses.

![image](https://user-images.githubusercontent.com/33934979/116728841-f3e60b80-a9d5-11eb-92aa-e297ce1b19f0.png)

![image](https://user-images.githubusercontent.com/33934979/116728869-fe080a00-a9d5-11eb-90c1-503944f221a3.png)

**Comment by ClotildeToullec** [comment]
Fixed 3388f98842e48382e54001eb56431225caadb8b6
