### ISSUE TITLE
Error MiCriticBrowserModel >> miSelectedItem not implemented

### ISSUE THREAD

**Issue by NicolasAnquetil** [moosetechnology/MooseIDE#1134]
The method is called when trying to tag a result with the tag button in the toolbar (see also #1117)

Note that the method is not called when propagating or inspecting a result .
It is strange that These two do not use the same behavior had the tagging process (but I don't know which behavior should be considered correct)

**Comment by ClotildeToullec** [comment]
This is fixed for MiCritic Browser. Second aspect is described in #1163
