### ISSUE TITLE
Library menu loads FAST-JAVA instead of FAST-Java

### ISSUE THREAD

**Issue by NicolasAnquetil** [moosetechnology/MooseIDE#1139]

**Comment by NicolasAnquetil** [comment]
I did the change but the PR fails on unrelated test.
The commit just changes hte name of the repo in:
```st
MooseLoadFASTJavaMenuCommand >> repositoryURL

	^ 'github://moosetechnology/FAST-JAVA:' , self version , '/src'
```
(and puts: `'github://moosetechnology/FAST-Java:' , ...`)

but the error in the CI is:
![Screenshot from 2024-07-25 14-56-04](https://github.com/user-attachments/assets/52544c4d-eae7-4524-88da-6ee191a89f87)

???

Any idea ?

**Comment by jecisc** [comment]
This got broken during the last Moose Dojo but Gabriel is in holidays I think. Clotilde is looking at this issue.
