### ISSUE TITLE
Navigation of models is **horrible**

### ISSUE THREAD

**Issue by badetitou** [moosetechnology/MooseIDE#1141]
I really ***hate*** the navigation pane of a model!

When you have a model that do not have classes, methods, enums, etc. It still displays them. 
I do not get how we can still live with that

I have cases with no code model, but also with basic models such as FAST.
I can create specific method for my own model, but I still don't get why we keep the entries for all model that might be not concerned

![image](https://github.com/user-attachments/assets/78f928fc-4756-48ef-9b90-82cc0b15453e)

**Comment by NicolasAnquetil** [comment]
yeah ! Go for it !

**Comment by fuhrmanator** [comment]
I agree -- TypeScript has other things than "attributes" (they're called properties) but I've wondered how that should be personalized for Moose. A more dynamic browser would be great - even one that has an option to show elements from the MM (that aren't present, perhaps grayed out?) and ones that are.

**Comment by badetitou** [comment]
I'm trying a revamp of the UI
https://github.com/moosetechnology/MooseIDE/pull/1142

I'll try to have the model pane based more on meta description 

And to have more info when inspecting an entity ( like also having the moose properties and having the name of the entities. So when you inspect a method. The relations parent will additionally display the moose name of the parent )

**Comment by jecisc** [comment]
I did not see this issue but today I was tired of this UI while working on a Python importer and I did some changes to show only elements that have values and also I added a column to display the number of elements of each properties.

![image](https://github.com/user-attachments/assets/e801e1d6-3773-49bf-9bb7-57c1e1b8b7da)

**Comment by jecisc** [comment]
I don't know if we should keep this issue opened since you have a draft to improve it or if this is enough. (I did something fast so it's possible that your draft will be better than what I did)

**Comment by NicolasAnquetil** [comment]
can you merge both you changes ?
are they compatible ?

**Comment by badetitou** [comment]
I merged both in my PR. I think the PR is ready. Maybe not as full replacement for now. But so everybody can test it

**Comment by NicolasAnquetil** [comment]
But now we lost the All**Model**Classes/Packages/Methods/... in the process.

This is unfortunate because it was the most useful.
I propose to keep this simplified list, but with non stub entities instead of all entities.

And then close the issue...

**Comment by badetitou** [comment]
Ok. We can add them back in the list ;)

**Comment by NicolasAnquetil** [comment]
Just to be clear, I am not proposing to go back to the previous situation.
I like the new short list, I am just proposing that allClasses / allMethods / ... give actually all-non-stub-classes/methods/...

I think it makes sense for newbies, and if somebody really needs the behavior of old allClasses/allMethods/... (ie including stubs) then they will have to use a pharo query: `model allWithType: FamixTClass`

**Comment by badetitou** [comment]
This is what I understood ;-) 

I merged an improvement. 

Now the navigation for models shows the group for entities. And then the group for *Model Entities* 

Do not hesitate if you think it can be even more improve
