### ISSUE TITLE
Model browser - no possibility to navigate between screen while creating ST models

### ISSUE THREAD

**Issue by anneetien** [moosetechnology/MooseIDE#1147]
- Open a model browser
- click on ST
- click on Advanced settings
- deselect or not some check box
- click on import
- a pop up window appears but there is no way to click on the previous screen.
<img width="506" alt="image" src="https://github.com/user-attachments/assets/b79b4f4e-9a14-42b5-ac93-19bd6fd1afc6">

There is no way to navigate between the screns.

**Comment by NicolasAnquetil** [comment]
Right, the problem is that "cancel" does not go back to the previous screen, but close the window

**Comment by ClotildeToullec** [comment]
This is a spec issue: the window used to change extent and this is broken.
We change the behaviour to fix this.
