### ISSUE TITLE
MoosePlayground should not have 2 toolbars

### ISSUE THREAD

**Issue by NicolasAnquetil** [moosetechnology/MooseIDE#1171]
![image](https://github.com/user-attachments/assets/42ab2e57-3637-44da-883a-25cd1d6a52bd)

Should merge the two toolbars into one

**Comment by ClotildeToullec** [comment]
Fixed https://github.com/moosetechnology/MooseIDE/commit/b194fcab8a5a03a9e3dacbb6d65c99ce4846c0d8
