### ISSUE TITLE
Rationalize MooseIDE tools (remove duplicates, rename, ....)

### ISSUE THREAD

**Issue by NicolasAnquetil** [moosetechnology/MooseIDE#121]
There are many MooseIDE tools with sometimes unclear functions, and other times confusing names (eg the "Model browser" and the "MooseModel browser" ; or the "Tree" and "Tree visualization" in Dependencies).

Also, now that we have an inspector, some tools (MooseModelBrowser) could be (already are) integrated into it.

I would like to first identify a core set of tools
- Model browser (to import models)
- Overview
- queries
- logger
- inspector
- source code
- some visualization ?

**Comment by anneetien** [comment]
This seems to be no more relevant
