### ISSUE TITLE
Integrate all tools into the MooseInspector?

### ISSUE THREAD

**Issue by NicolasAnquetil** [moosetechnology/MooseIDE#122]
Now that we have the MooseInspector, many (all?) tools could be integrated into it, or possible to integrate into it like I did with the OverviewBrowser

**Comment by badetitou** [comment]
I'm not sure it would make sense to have all the tools in the inspector.
I would go for having some tools by default (let's say the ones we had in Moose8)

And why not a configuration (with checkboxes). 
Then, users can select a tool they want in the inspector or not.
