### ISSUE TITLE
The Moose Playground has no model bindings

### ISSUE THREAD

**Issue by LABSARI** [moosetechnology/MooseIDE#1238]
The bindings to access moose models from the playground are absent.
Version: Moose 12
![image](https://github.com/user-attachments/assets/b795f1ba-e58d-45fd-91f0-f78ced83b33b)

**Comment by ClotildeToullec** [comment]
Is your image up to date? I have fixed that this week

**Comment by LABSARI** [comment]
It was on an image downloaded that day.
