### ISSUE TITLE
Bug with the drag&drop functionality in models browser

### ISSUE THREAD

**Issue by Marpioux** [moosetechnology/MooseIDE#1254]
Hi, I’m experiencing an issue with Moose12. When I attempt to drag and drop a Moose model (in JSON format) into the model browser, I encounter the following problem:
![image](https://github.com/user-attachments/assets/0fd84200-affc-43d0-8c43-cb283545d485)

Does anyone have suggestions on how to resolve this?
Thank you!

**Comment by NicolasAnquetil** [comment]
thank you for reoprting.
I could replicate the bug, we will have a look and come back to you.

**Comment by NicolasAnquetil** [comment]
Problem comes from MiApplication >> openCurrentModelsBrowser
When the browser exist:
```st
	currentModelsBrowser
		  ifNotNil: [ :modelsBrowser |
			  modelsBrowser withWindowDo: [ :window |
				  window
					  restore;
					  activate ] ]
```
returns the window and not the MiModelsBrowser

**Comment by NicolasAnquetil** [comment]
this is a possible solution:
```st
openCurrentModelsBrowser

	^ currentModelsBrowser
		  ifNotNil: [ :modelsBrowser |
			  modelsBrowser withWindowDo: [ :window |
				  window
					  restore;
					  activate ] ;
					yourself ]
		  ifNil: [
		  currentModelsBrowser := MiModelsBrowser instantiateAndOpen ]
```

**Comment by Marpioux** [comment]
It worked perfectly—thank you!

**Comment by NicolasAnquetil** [comment]
Still need to validate the proposed solution and integrate it

**Comment by ClotildeToullec** [comment]
I implemented your solution @NicolasAnquetil and added a test for it.
