### ISSUE TITLE
Allow to create a RootQuery as child of another query

### ISSUE THREAD

**Issue by NicolasAnquetil** [moosetechnology/MooseIDE#128]
It could be nice if we could include results from another tool as a new RootQuery in a branch.
example:
Have 2 query browsers opened. One produces a 1st result. 2nd browser produce a 2nd result and allows to combine it (union, intersection) with first result.

We could do this by creating a 2nd RootQuery in the 2nd browser, and the 2nd Root query would listen to a different bus.

This was extracted from #126

**Comment by anneetien** [comment]
Is this issue still relevant?
@NicolasAnquetil @jordanmontt @LABSARI
