### ISSUE TITLE
Remove MooseFinder and MoosePanel

### ISSUE THREAD

**Issue by jordanmontt** [moosetechnology/MooseIDE#193]
Remove the old inspector. It is called MooseFinder.

**Comment by akevalion** [comment]
Where is the repository of Moose-Finder package?
Because it is not here https://github.com/moosetechnology/MooseIDE

**Comment by jordanmontt** [comment]
Sorry for the late replay.
But Moose Finder is in this repo: https://github.com/moosetechnology/Moose

**Comment by anneetien** [comment]
MoosePanel and MooseFinder are no more in the image.
