### ISSUE TITLE
Fix MiInspectorBrowserTest failing on CI.

### ISSUE THREAD

**Issue by ClotildeToullec** [moosetechnology/MooseIDE#223]
These tests pass on a Moose Image locally but fail on CI.
This is under investigation.

Tests have been excluded on the CI (file: .smalltalk.ston) for MooseIDE and Moose projects.

**Comment by anneetien** [comment]
It seems that this issue is no more relevant.
@ClotildeToullec if needed, please feel free to reopen the issue
