### ISSUE TITLE
TagBrowser: exception when opening TagDetails page without a model

### ISSUE THREAD

**Issue by ClotildeToullec** [moosetechnology/MooseIDE#225]
When no entities have been propagated on the bus, the tag browser throws an error when trying to open the  'Tag details' page.
This case should be handled to inform the user without throwing an error.

**Comment by NicolasAnquetil** [comment]
I did that somewhere in the past.
May be I forgot to merge ?
will investigate

**Comment by anneetien** [comment]
@NicolasAnquetil is it still relevant?
