### ISSUE TITLE
Rewrite Glamour Inspector tabs with Spec ones

### ISSUE THREAD

**Issue by ClotildeToullec** [moosetechnology/MooseIDE#252]
Check for old pragma `<moosePresentationOrder: ...>`: are these methods called somewhere?

Check features from Moose Playground: 
- If they are needed, use them elsewhere or extend the new playground?
- If they are not, remove them

then remove the old playground

**Comment by jordanmontt** [comment]
The methods with the pragma `<moosePresentationOrder: ...>` are collected by the old Moose inspector (the one written in glamour). We should rewrite this methos to:
1. Use the pragma `<inspectorPresentationOrder:title:>`
2. To return a Spec presenter

**Comment by anneetien** [comment]
<moosePresentationOrder: ...> pragma is no more used in Moose
