### ISSUE TITLE
Use #displayStringOn: instead of #printOn: in the inspector

### ISSUE THREAD

**Issue by ClotildeToullec** [moosetechnology/MooseIDE#253]
We don't want to see 'a FamixStClass' in the inspector, at least in the specialized lists (like in the Navigation tab).

**Comment by jordanmontt** [comment]
Yes, we should check all of the moose inspector panes and put nicer strings

**Comment by LABSARI** [comment]
Corrected here : https://github.com/moosetechnology/Famix/pull/381.
