### ISSUE TITLE
Add test coverage badge

### ISSUE THREAD

**Issue by jordanmontt** [moosetechnology/MooseIDE#278]

**Comment by jordanmontt** [comment]
Perhaps @badetitou can teach us how to do it? 😄

**Comment by jordanmontt** [comment]
![Screenshot 2021-09-10 at 16 26 00](https://user-images.githubusercontent.com/33934979/132869292-06b07318-2950-4135-bf17-f08c4a4235bc.png)

**Comment by badetitou** [comment]
done
