### ISSUE TITLE
Blueprint inspector tab not working properly

### ISSUE THREAD

**Issue by NourDjihan** [moosetechnology/MooseIDE#280]
When creating a Moose model then inspecteur a FamixStClass then selecting Blueprint tab in the Moose inspector
<img width="794" alt="Screenshot 2021-09-13 at 14 55 12" src="https://user-images.githubusercontent.com/34944559/133087254-35dcb938-2264-4f90-8afd-731e20122aae.png">

**Comment by anneetien** [comment]
It seems that this issue is no more relevant.
I close the issue, @NourDjihan if needed you can reopen it.
