### ISSUE TITLE
Durden workspace

### ISSUE THREAD

**Issue by NicolasAnquetil** [moosetechnology/MooseIDE#287]
Durden workspace allows to group several tools in one window.

It is a MiBrowser, so it listens and writes on bus(es)

It has an "internal bus" that it's children browsers listen and write

The workspace make the bridge between external bus(es) and its internal bus:
- takes incoming entities on external bus and send them on internal bus,
- takes entities on internal bus to propagate them on external bus(es).
- propagation on internal bus is automatic,
- propagation to external bus(es) is on demand

**Comment by anneetien** [comment]
@NicolasAnquetil @ClotildeToullec Is this issue still relevant?
