### ISSUE TITLE
Generic "architecture" for MiAbstractBrowser

### ISSUE THREAD

**Issue by NicolasAnquetil** [moosetechnology/MooseIDE#288]
Related to #287 : all browser should offer a presenter for their "content" (what is below the generic toolbar: highlight/follow/freeze ; buses ; propagate ; drag buttons)

Thus all browsers are implemention of the same MiEmbeddableBrowser which as this toolbar and an unspecified content.
The content is defined separately by each browser. This content can be embedded in a MiEmbeddableBrowser or a MiDurdenWorkspace

**Comment by ClotildeToullec** [comment]
A nice solution would be to simply follow Spec rules and have a `MiWindowPresenter` with the toolbar included.
We would just choose to open browsers in a MiWindowPresenter or in a MiDurdenWorkplace.

I actually tried to do this on Monday BUT Spec toolbar does not allow radio buttons.
So, possible solutions: 
1- We do what you proposed
2- We say goodbye to radio buttons in the toolbar and find another way to display Freeze/Follow/Highlight
3- We try to include radio buttons to a toolbar (and make a PR to Spec)

**Comment by NicolasAnquetil** [comment]
Your solution seems great.
What can we put in the toolbar ?
- a DropBox (with the 3 options follow/highlight/freeze)
- some kind of menu with the 3 options (and showing which one is currently selected)
- 3 normal buttons and clicking on one would "gray-out" the other two

**Comment by ClotildeToullec** [comment]
You have an example of a toolbar when executing `SpToolbarPresenter example`. 
I like the menu best aesthetically (the last item on the example), but it's 2 clicks to change instead of 1.
The option of 3 normal buttons is also available, I think we can change their appearance when not active.

**Comment by NicolasAnquetil** [comment]
I just checked: when a SpToolbarButtonPresenter is disabled, (1) it is grayed out, and (2) one can still click on it and get the information (`#action` is executed).
This is strange, but it fits the behaviour we need:
- 3 buttons
- make sure only 1 of them is enabled at anytime
- clicking on a disabled one -> enables it and disables the 2 other ones
(may be we should check if this strange behavior is a bug or a feature of Spec ... ?

**Comment by NicolasAnquetil** [comment]
oups no.
it's a bug, not a feature. When creating a SpToolbarButtonPresenter with `enabled: false`, you can click on it, but after that, when changing the state of a button to `enabled: false`, you can no longer click ...

**Comment by ClotildeToullec** [comment]
An example of what it could look like (with or without a browser-specific toolbar): 
- It's not possible to have items in the center (like the bus button before).
- The radio buttons are fake, I'm just changing the icon
- We cannot change the size of the buttons (I think)
- We could add the items of the browser-specific toolbar to the window toolbar, not sure we want it?
- The edit icon does not seem right for the buses button

![Capture d’écran 2021-09-22 à 11 54 14](https://user-images.githubusercontent.com/39184695/134322992-b099af93-1450-4076-8ae2-192a5a6c175d.png)

![Capture d’écran 2021-09-22 à 11 54 05](https://user-images.githubusercontent.com/39184695/134322978-bccb300c-7389-40d0-aef8-586a76c4e73b.png)

**Comment by NicolasAnquetil** [comment]
looks great to me.
"default" is for the bus ? If so, it should say so.
Again, it could be a menu for the bus, because their can be several

**Comment by anneetien** [comment]
It seems this issue has been solved. 
If not, @NicolasAnquetil @ClotildeToullec please reopen this issue
