### ISSUE TITLE
Selectable lines in QueryBrowser result pane

### ISSUE THREAD

**Issue by NicolasAnquetil** [moosetechnology/MooseIDE#290]
bottom list of QueryBrowser is currently "read-only"

we want to be able to select one or more entities in this result to propagate it (for example: to a browser displaying the source code of one entity)

**Comment by jordanmontt** [comment]
@NicolasAnquetil  the "bottom list" of the Queries Browser is already multi-selectable and propagates the selected result(s).

**Comment by jordanmontt** [comment]
If you click on a result and click the propagate button you will see that the result is propagated. For multiple selection you have to select the results with the shift key (on Mac)
