### ISSUE TITLE
Query on tags

### ISSUE THREAD

**Issue by NicolasAnquetil** [moosetechnology/MooseIDE#291]
we want to be able to query entities on the tags they have (or not)

**Comment by jordanmontt** [comment]
- Queries can return tags (String, Boolean, Scope, etc)
- New queries on tags
    - isTagged? (with tag "xyz")

**Comment by jordanmontt** [comment]
This is related with #104

**Comment by NicolasAnquetil** [comment]
Query browser relies on the following:

- FamixTag should use FamixTNamedEntity
  https://github.com/moosetechnology/Famix/issues/418
- FamixTag should use TEntityMetaLevelDependency
  https://github.com/moosetechnology/Famix/issues/419
- FamixTag >> #description should be renamed (?)
  because it overrides `MooseEntity >> #description`

**Comment by NicolasAnquetil** [comment]
already done I believe
