### ISSUE TITLE
Data exchange mechanism between tools

### ISSUE THREAD

**Issue by NicolasAnquetil** [moosetechnology/MooseIDE#292]
We need a way to share different things between tools:
- The bus allow to share entities
- We want to share also queries (not their result, but the query itself)
- Santi needs to share configuration between his tools

Ideas could be
- announcement mechanism (MiApplication will be the announcer)
- different kind of buses: entity bus, query bus, ...

But these solutions use a "push communication model": QueryBrowser *announce* a new available query, interested browsers take note of it to be used later.

It seems better to use a "pull communication model": browser A *requests* all available queries, QueryBrowser give the list.

So it requires a model with a broker (or registry) were browser can register to serve specialized data

Subscribing to Query/Property annoucement/bus should be automatic for the interested browsers and transparent for the user

**Comment by ClotildeToullec** [comment]
@sbragagnolo `We can evaluate it during the sprint, along with the composable container.`
Yes
