### ISSUE TITLE
Hierarchical Map with Properties

### ISSUE THREAD

**Issue by NicolasAnquetil** [moosetechnology/MooseIDE#295]
Displays incoming entities in a HierarchicalView (#286 ;  https://github.com/ObjectProfile/HierarchicalVisualizations)

Tool has a configuration where one can select a list of properties (taken from PropertyBrowser #293)

For each displayed entity, if it matches one property query, it will get the color of the property.

If an entity match several queries, 2 options:
- give a specific color (black, gray, red)
- use anyOne of the matching properties

**Comment by anneetien** [comment]
It is an Architectural view with Tag?
@NicolasAnquetil

**Comment by NicolasAnquetil** [comment]
I think it was a kind of "dynamic tag"
But the question remains on how to display several "tag" colors in a view.
I think the right solution is to use the muti-colored icon that we now have

Choosing one of them is not good because it is misleading
