### ISSUE TITLE
Distribution Map

### ISSUE THREAD

**Issue by NicolasAnquetil** [moosetechnology/MooseIDE#296]
We want a distribution map browser

Probably based on the prototype in [https://github.com/NicolasAnquetil/HierarchicalVisualizations](https://github.com/NicolasAnquetil/HierarchicalVisualizations) not on the telescope one

Will work somehow like #295, but the Distribution map wants exactly 2 levels of entities: Containers and members

So we need to force this:
- entities coming from the bus should be of that form => user responsible for selecting the right entities with the proper query
- entities coming from the bus are the containers and the tool accept one query that will produce members for each of these incoming container

(second solution seems best)

**Comment by anneetien** [comment]
The distribution map is currently available.
