### ISSUE TITLE
System complexity

### ISSUE THREAD

**Issue by NicolasAnquetil** [moosetechnology/MooseIDE#297]
Recreate the system complexity browser (3 metrics displayed with width, height, and color of boxes)
Entities are displayed in a tree

Possibly accept colored properties (same as #295) and then it would have only 2 metrics with width and height of boxes

Possibly starting at a given level, containment is not shown as a tree, but as a HierarchicalVisualization (nodes inside nodes)

**Comment by anneetien** [comment]
System complexity Browser is currently existing.
