### ISSUE TITLE
FavoriteBrowser

### ISSUE THREAD

**Issue by NicolasAnquetil** [moosetechnology/MooseIDE#298]
A tool to record some favorites "things" that the user like:
- shortcut to a tool often used
- a shortcut to a DurdenWorkspace with a given configuration
- a "favorite" query (and the tool would be a provider of queries, see #292)
- a "favorite" Property (see #293)

**Comment by anneetien** [comment]
There are shortcut for Model browser, Query browser and tag browser.
Durden is not implemented yet.
