### ISSUE TITLE
Moose Inspector Navigation tab is awfull to use

### ISSUE THREAD

**Issue by badetitou** [moosetechnology/MooseIDE#299]
When using the moose inspector to inspect a Moose Model, it **always** show useless entry in the table.

For instance, it presents the concepts present in the meta-model -> OK
And several `All xxx`

![image](https://user-images.githubusercontent.com/6225039/134296261-0a01d4fa-d2a6-43b0-9601-5bd19edbaea4.png)

When I inspect a model of FAST, I do not care about the `all accesses` entry that can not exist in my context.
We should kill them or make them smarter (for example, attaching the `all xxx` to a concept or group of concepts, or a metamodel)

IMO, preliminary work can be done during a sprint

**Comment by NicolasAnquetil** [comment]
Eliminating the entries for which there is 0 entity could be a first simple step.

Would that be enough for you?
Do you need more ?

**Comment by badetitou** [comment]
It would be ok
