### ISSUE TITLE
In Spec filtering list when passing the items is the same object

### ISSUE THREAD

**Issue by jordanmontt** [moosetechnology/MooseIDE#305]
When youu set the elements of a sp filtering list (and a filtering selectable list also) the items object is the same object as the original list. Which can lead to misleading behaviours

**Comment by anneetien** [comment]
@jordanmontt is this issue still relevant? It seems to be a Spec issue. Does it make sense to keep it here?

**Comment by jordanmontt** [comment]
Hello, this is not an spec issue but I think that is not relevant anymore. So I will close it.
