### ISSUE TITLE
rename RootQuery in the queryBrowser

### ISSUE THREAD

**Issue by NicolasAnquetil** [moosetechnology/MooseIDE#308]
The root query is the parent of (most) top level queries
but actually, it is not a query, it i just something to hold the set of entities coming from the bus
It could be named:
- incomingEntities
- workingSet
- rootData
- ...

**Comment by jordanmontt** [comment]
I will move this to Famix Queries

**Comment by jordanmontt** [comment]
because is not in the queries browser but in famix queries
