### ISSUE TITLE
propagation strategy buses

### ISSUE THREAD

**Issue by NicolasAnquetil** [moosetechnology/MooseIDE#323]
Following #320, we could have at least 3 kind of buses:
- push bus: when data is written on the bus, it immediately transmits it to all tools attached to it
- delayed bus: when data is written on the bus, it stores it and only transmits when there is an explicit "flush" from the producer (allow to work with the "Propagate" button of the tools)
- pull buses, bus stores data and does not transmit it unless explicitly asked by a receiver tool
The last 2 are a bit similar: one is a *flush* from the producer to all consumers the other is a *flush* from the consumer only to itself.

**Comment by anneetien** [comment]
do we have use cases of these?
@NicolasAnquetil
