### ISSUE TITLE
JSON icon is unintelligible on dark theme

### ISSUE THREAD

**Issue by jordanmontt** [moosetechnology/MooseIDE#326]
![Capture d’écran 2021-10-15 à 10 41 41](https://user-images.githubusercontent.com/33934979/137458927-25ff76ae-4f92-4d8b-8793-9d7596e4dde5.png)

**Comment by LABSARI** [comment]
@jordanmontt This issue is corrected in the Famix repo: https://github.com/moosetechnology/Famix/pull/374
