### ISSUE TITLE
Do not use fixed constraints in presenters, use styles instead

### ISSUE THREAD

**Issue by jordanmontt** [moosetechnology/MooseIDE#336]
Currently, in all of the presenters we are using fixed constraints like height and width. For example: `add: presenter width: self class buttonWidth`. Which is not the correct way. We should use custom styles that we need to define in the MiApplication class.

We can use this blog post as a guide on how to use styles
https://thepharo.dev/2021/10/25/using-styles-in-spec-applications/

**Comment by anneetien** [comment]
@ClotildeToullec does-it make sense?

**Comment by ClotildeToullec** [comment]
It does

**Comment by ClotildeToullec** [comment]
Actually no, I close this. Constraints used when using layouts can't be moved to the presenter style.
