### ISSUE TITLE
MiAbstractBrowser>>ifAutonomous is specific to MiLogBrowser ?

### ISSUE THREAD

**Issue by NicolasAnquetil** [moosetechnology/MooseIDE#344]
Does not look like something that other browsers will use ?

**Comment by anneetien** [comment]
ifAutonomous: is not called.
I removed the method and all tests are passing.
Do we need to keep the method? and if it is the case where in MiAbstractBrowser or MiLogBrowser or should we simply remove it?
@NicolasAnquetil
