### ISSUE TITLE
When saving queries an exception is raisen

### ISSUE THREAD

**Issue by jordanmontt** [moosetechnology/MooseIDE#347]
Sometimes when saving queries in the queries browser the debugger is open or the image hanges

**Comment by jordanmontt** [comment]
I am investigating a little and this error happens only when a NAry query is present.

**Comment by jordanmontt** [comment]
Actually not only NAry queries but any query that uses another query. (NAry query, FQComplementQuery, FQResultSizeQuery)

**Comment by LABSARI** [comment]
I could not reproduce the issue.
