### ISSUE TITLE
MiQueriesBrowserTest>>testActivateActionButtons fails for Inspect button

### ISSUE THREAD

**Issue by NicolasAnquetil** [moosetechnology/MooseIDE#348]
Inspect button not disabled by default.

Is it normal ?

**Comment by NicolasAnquetil** [comment]
Same for Propagate button

Note trying this in new architecture with Workspace

**Comment by jordanmontt** [comment]
- I think that the inspect button should not be disabled in the queries browser.
- Also I think that the propagate button should be enabled.
- I run all the MiQueriesBrowser and they are passing in a new moose image.

**Comment by NicolasAnquetil** [comment]
As far as I understand, the behaviour is that as lng as there is nothing in a Browser, you cannot propagate or inspect and therefore the buttons should be disabled
see with @ClotildeToullec

**Comment by ClotildeToullec** [comment]
Yes, that was the intention. Nicolas, you're right, if we follow this rule, the buttons should be disabled by default.
If you think we should do things differently @jordanmontt , we can discuss it of course.

To understand this issue: @NicolasAnquetil you created `MiQueriesBrowserTest>>testActivateActionButtons` or refactored it to the superclass (I agree with this) and it does not work properly?

**Comment by NicolasAnquetil** [comment]
Yep something along these lines. I don't remember exactly to be honest

**Comment by LABSARI** [comment]
Can't find test.
