### ISSUE TITLE
A MiLogger is created for every new MiBus ?!

### ISSUE THREAD

**Issue by NicolasAnquetil** [moosetechnology/MooseIDE#349]
The same logger can have several buses, so why create one in the constructor ?

**Comment by akevalion** [comment]
I have created a shared logger provided by the application, each time the application creates a bus, is going to use the logger of the application

**Comment by ClotildeToullec** [comment]
The PR fixes the issue.
However, we lose the information "on which bus this was propagated".
The logger should have a dictionary { bus -> logs } instead of a simple collection of logs.
Each time a log is needed, it is added only for the corresponding bus.
