### ISSUE TITLE
unify all #testMiSelectedItem in MiAbstractBrowserTest

### ISSUE THREAD

**Issue by NicolasAnquetil** [moosetechnology/MooseIDE#352]
very similar to #346 with another method

**Comment by anneetien** [comment]
test methods are really different here.
Only 9 classes get the testMiSelectedItem method over 22 classes. Consequently, we may add more methods than we delete and for the existing one, not sure there is no overridding.
Not sure concretely it worth it.
@NicolasAnquetil
