### ISSUE TITLE
Negation query not working

### ISSUE THREAD

**Issue by NicolasAnquetil** [moosetechnology/MooseIDE#358]
on a FamixSt model for LAN-model, do a boolean query isStub, then a negation on this and the result is empty

**Comment by ClotildeToullec** [comment]
Problem is: the droplist proposing queries to negate does not select the first query by default. 
The negation query is invalid until you actively select a query to negate.

Solution: select the first query in the droplist without any need for user action.

Note: we should check for similar bugs in the other types of queries

**Comment by NicolasAnquetil** [comment]
migrated to a new issue
