### ISSUE TITLE
Negation query 'Current query code' tab is incomplete

### ISSUE THREAD

**Issue by NicolasAnquetil** [moosetechnology/MooseIDE#359]
only gives:
`FQComplementQuery`

**Comment by jordanmontt** [comment]
i couldn't reproduce the issue. For me is working on a new moose image.

<img width="653" alt="Capture d’écran 2021-11-17 à 10 44 34" src="https://user-images.githubusercontent.com/33934979/142176602-00cc823e-fe13-44ab-bdb5-52814ffed087.png">

**Comment by NicolasAnquetil** [comment]
Another manifestation of #364
