### ISSUE TITLE
Blueprint is broken for FamixJava Model

### ISSUE THREAD

**Issue by badetitou** [moosetechnology/MooseIDE#361]
The blueprint is broken when analyzing a FamixJavaModel.

It might be a missing method in Famix, or a problem in MooseIDE

![image](https://user-images.githubusercontent.com/6225039/141941476-e547e0ea-79dd-4feb-a490-1e6b3b40fafe.png)

**Comment by anneetien** [comment]
Hello,

BluePrint has been modified. We need to use the version of Nour that normally works for Java Models. 
Anne

**Comment by anneetien** [comment]
see #395

**Comment by ClotildeToullec** [comment]
Nour's work has been integrated, so now we use her version of the Class Blueprint
