### ISSUE TITLE
Bug loading query

### ISSUE THREAD

**Issue by badetitou** [moosetechnology/MooseIDE#367]
I tried to save on query on disk and load it in another QueryBrowser but it fails.
What I did:

- Load a model
- Perform query to retrieve some classes (image)
![image](https://user-images.githubusercontent.com/6225039/143012536-09a2948f-4bbc-4d99-9226-44e191a17350.png)
- Save the query (and freeze the current query browser)
- Open a new query browser
- Propagate the original model to the newly opened query browser
- Load the past created query

**Bug**

![image](https://user-images.githubusercontent.com/6225039/143012829-7888598d-8804-4ec7-9d82-faed0f1247ef.png)

**Comment by badetitou** [comment]
(I used a model generated from the RCA application that can be found in https://badetitou.fr/files/rcaexplore.zip )

**Comment by LABSARI** [comment]
We can not reproduce the bug. Maybe it has been fixed.
