### ISSUE TITLE
Propagate to a Moose Playground

### ISSUE THREAD

**Issue by badetitou** [moosetechnology/MooseIDE#368]
I would love to be able to propagate entities to a Moose Playground.
It would ease manipulating entities in a custom way (for example after performing a nice FamixQuery).

- [ ] Propagating to MoosePlayground would store the propagated entities in a specific variable.
Or store in the playground dictionary the entities (maybe it is the same dictionary as the one of the logger?)
- [ ] When a new entity is received, the playground can `doit` the script with the newly received entity (auto-update script?)
- [ ] A new command in the menu `Propagate It` that works as `DoIt`, `InspectIt`, _etc._ but that propagates the result

**Comment by NicolasAnquetil** [comment]
Yes, nice idea, the MoosePlayground could have a (small) set of "predefined entities":
- `currentModel` that can be set from the magic button you created
- `currentSelection` (or `selectedEntities`) for the last propagated set of entities
- `currentDirectory` (or `rootDirectory`) following #369 and also #367)

**Comment by NicolasAnquetil** [comment]
I think we already have the `PropagateIt` action ?
@ClotildeToullec ?
Anyway it is a nice idea too.

But I am not so sure about the automatic `DoIt` action it could easily raise havoc

**Comment by ClotildeToullec** [comment]
I've also been wondering about this.
In the end, are we not talking about a "playground browser"? Not sure.
Do we want all this in the default playground or only when using a playground in relation to the other browsers?
Anyway, I'm quite sure it will not be very hard.

**Comment by badetitou** [comment]
It is not the default playground.
It is the Moose Playground.

Let's rename it Playground Browser if you want 😸 
Still, in my opinion, this browser is super important.

Currently, we have to do: `inspectIt`, and in the inspector, use the hidden script area

**Comment by badetitou** [comment]
It is not the default playground.
It is the Moose Playground.

Let's rename it Playground Browser if you want 😸 
Still, in my opinion, this browser is super important.

Currently, we have to do: `inspectIt`, and in the inspector, use the hidden script area

**Comment by ClotildeToullec** [comment]
I wasn't clear. When I say "browser" I mean embedded in Moose tools, with the toolbar and the buses mechanism.

I'm thinking in parallel with the inspector: we chose to continue using the pharo inspector when inspecting from anywhere else than Moose, and the Moose Inspector browser only from Moose tools.

The way I started modifying the playground was not in the same mindset: it is the pharo playground with small additions, and it's installed as the default playground in the system. If we want to receive and propagate entities, we will end up having a "browser": a playground embedded in a Moose window with buses mechanism.

If we do that, do we want it 
- to be installed in the system as the default playground (and then why not the Moose inspector?)
- to open it only when we want the "browser" behavior?

**Comment by anneetien** [comment]
Nothing done after almost 3 years. Is it still up to date?
@badetitou @NicolasAnquetil @ClotildeToullec

**Comment by NicolasAnquetil** [comment]
Yes I think it is still valid.
And my idea of having some "predefined variables" (first answer at the top) does not seem to difficult to implement (?)

- `mooseModel` we already have it in the playground so not needed anymore
- `mooseSelection` (or `selectedEntities`) depends  on the bus, so it should be a mechanism similar to the models but for each different bus (and their content)
- `mooseDirectory` (or `rootDirectory`) not sure about this one, but may be?
