### ISSUE TITLE
Propose a better choice for files when setting root folder

### ISSUE THREAD

**Issue by ClotildeToullec** [moosetechnology/MooseIDE#369]
Now the file chooser opens on the working repository. Ideally it would propose the file where the .ston/.mse file was found to load the model.

**Comment by NicolasAnquetil** [comment]
No, not done really:
You can select the root directory from the mse/json directory when you import.
But if you forget to do it at that time, then trying to correct the error will reset you at the image directory (or the user's home directory?)

So could be reopened, except that after so much time, nobody really seemed to need it...
