### ISSUE TITLE
change list of properties in queries

### ISSUE THREAD

**Issue by NicolasAnquetil** [moosetechnology/MooseIDE#398]
Currently, the list of available properties for a query (BooleanQuery, NavigationQuery, RelationQuery, StringQuery) is the **intersection** of compatible properties for all entities in the bus.

So if we have a hundred classes and methods on the bus and one FamixComment, the `name` property will not be proposed because comments have no name.

I think it would be better to offer the **union** of all compatible properties and have an appropriate default behavior if an entity is asked a property it does not have (like asking the name of a FamixComment).

**Comment by badetitou** [comment]
Why not? I try to find some cons.

- Too many properties displayed? 
- How to identify which property is linked to which concept? (Class, Method, Comment...)

Maybe the properties of the list can be sorted depending on their _compatibilities_ with the source entities (classes, methods, comments).

Or a new kind of list with sub-title.
Something like a list with sections?

![image](https://user-images.githubusercontent.com/6225039/147855664-63d8c514-1960-4e7f-b136-2f84e6402cf1.png)
