### ISSUE TITLE
Cannot inpect an entity in the script area of MiInspector

### ISSUE THREAD

**Issue by badetitou** [moosetechnology/MooseIDE#404]
When inspecting an entity computed in the MiInspector, it raises an exception (even if the inspected entity is a MooseObject).
![cannotInspect](https://user-images.githubusercontent.com/6225039/149986353-d91effca-8ac2-4d78-9a10-4441e8dcdf82.gif)

**Comment by anneetien** [comment]
I tried on a new image and there is no more raised exception. So I close the issue.
If needed, please feel free to reopen it.
@badetitou
