### ISSUE TITLE
Merge MooseModel browser and MooseProperty browser ?

### ISSUE THREAD

**Issue by NicolasAnquetil** [moosetechnology/MooseIDE#41]
Talking of the MooseModel browser at the time of this writing (see issue #39)

MooseModel browser and MooseProperties browser seem like two instances of a Moose "inspector" that show the details (properties,relationships) of the current entity.

Couldn't they be merged?
A bit like a pane of the MoosePanel, except that I would put two panes (vertical layout) for properties and relationships

**Comment by badetitou** [comment]
Sounds like a good idea to me

**Comment by anneetien** [comment]
It seems that MoosePropertyBrowser is no more in the image
