### ISSUE TITLE
ModelsBrowser should set a default root folder

### ISSUE THREAD

**Issue by NicolasAnquetil** [moosetechnology/MooseIDE#414]
for MSE/JSON files

set the root folder to the folder containing the MSE/JSON file

**Comment by badetitou** [comment]
I agree

Or the ModelBrowser can show a little icon like ⚠️  next to models that do not have root folder (for models like Java ones)

**Comment by NicolasAnquetil** [comment]
Nice work, but you forgot to solve the issue (new UI does not set a default root folder) :-)

**Comment by NicolasAnquetil** [comment]
I put an automatic update of root file folder input file from the file input path
