### ISSUE TITLE
CoUsageBrowser allow different sorting strategies for the elements

### ISSUE THREAD

**Issue by NicolasAnquetil** [moosetechnology/MooseIDE#419]
sorting of inner elements and outer elements

**Comment by akevalion** [comment]
Currently from canvas menu, users can open block settings, to modify the outer boxes and inner boxes sorting block.

Children block is not working yet
<img width="1294" alt="image" src="https://user-images.githubusercontent.com/10532890/152828511-f3ed79bc-9559-47b3-994c-f7558b62e904.png">
