### ISSUE TITLE
CoUsageBrowser configuration: threshold for automatic method tagging

### ISSUE THREAD

**Issue by NicolasAnquetil** [moosetechnology/MooseIDE#420]
This threshold should be configurable

**Comment by akevalion** [comment]
There is a new menu item por that menu. the threshold is between 0 and 1, default value is 0.75.
This value is used again each time user reopen the visualization.

![image](https://user-images.githubusercontent.com/10532890/151826322-74a00a27-0684-499f-af03-b8e4719f01c3.png)

![image](https://user-images.githubusercontent.com/10532890/151826604-0bfc379a-26b0-4204-a5f2-fcd2f1e1af64.png)
![image](https://user-images.githubusercontent.com/10532890/151826638-0123da8f-5f7e-4ae2-911c-e811fda51812.png)
![image](https://user-images.githubusercontent.com/10532890/151826665-ddb3ab22-d94b-49c8-8398-3d10e258b872.png)

**Comment by akevalion** [comment]
![image](https://user-images.githubusercontent.com/10532890/152313213-0cec5823-546f-4968-9811-7ad6655e5dea.png)

**Comment by akevalion** [comment]
Finally I have decided to use SettingsBrowser, accessed by the global menu

![image](https://user-images.githubusercontent.com/10532890/152348799-dec9fe14-15de-4c70-b345-ca7a2e862656.png)

**Comment by akevalion** [comment]
Done
