### ISSUE TITLE
CoUsageMap: tags ALL entities with "Need work" ?

### ISSUE THREAD

**Issue by NicolasAnquetil** [moosetechnology/MooseIDE#423]
After automatic coloring of methods display is correct but inspecting a method and asking it #tags will answer its correct tag + NeedWork

**Comment by akevalion** [comment]
Not reproducible,

![image](https://user-images.githubusercontent.com/10532890/152314636-85467c6a-c9d7-4fe7-885c-cb512b02fe85.png)

**Comment by akevalion** [comment]
This has been fixed
