### ISSUE TITLE
CoUsageMap does not read tags when opening

### ISSUE THREAD

**Issue by NicolasAnquetil** [moosetechnology/MooseIDE#424]
Open a CoUsageMap, tag attributes and methods
Then open a second CoUsageMap, it is completely blank :-(
It should show the attributes/methods already tagged (in the 1st one)

**Comment by akevalion** [comment]
Not reproducible
![image](https://user-images.githubusercontent.com/10532890/152314976-e0d776ba-3a03-44de-831f-9cf1bd921c1d.png)
