### ISSUE TITLE
cpp model should be integrated

### ISSUE THREAD

**Issue by akevalion** [moosetechnology/MooseIDE#438]
We will need somebody to integrate the old C++ meta model into latest
MooseIDE

code is there: https://github.com/jecisc/CPPS

We first need to integrate:
- the meta-model: CPPS-Generator, CPPS-Entities, CPPS-Entities-Tests
- the importer: CPPS-Parser, CPPS-Parser-Tests , CPPS-Generator (may
be)

May be Milton can look into that?

nicolas

**Comment by akevalion** [comment]
I have created repository with the new code 
https://github.com/akevalion/CPPS

But CPPS-Parser-Tests are not working

**Comment by NicolasAnquetil** [comment]
CPPSModel new give a message: `key 'FamixTType' not found in Dictionary`

**Comment by NicolasAnquetil** [comment]
and by the way, could you rename it CPP (or Cpp) without the S ?

**Comment by akevalion** [comment]
I have renamed CPPS=> Cpp.
All packages and classes names

**Comment by akevalion** [comment]
I have created a pull request for this issue

**Comment by akevalion** [comment]
That pull request is not going to be valid, then I have created this repository with last version of cpp meta model

https://github.com/akevalion/Famix-CPP

In a future maybe moosetechnology should create a project for that

**Comment by akevalion** [comment]
Cpp model is now here:
https://github.com/moosetechnology/Famix-Cpp
I have added on moose, a menu item to load the new Famix-cpp model
