### ISSUE TITLE
In tree map visualization browser, some entities can be present twice.

### ISSUE THREAD

**Issue by ClotildeToullec** [moosetechnology/MooseIDE#45]
If an entity is contained in another.
It is then present as itself and as an entity contained in the other.
![TreeMapVisu](https://user-images.githubusercontent.com/39184695/84178619-ff120f00-aa84-11ea-90d1-5fb6c5f0c832.png)

**Comment by anneetien** [comment]
@LABSARI is this visualization still in the image?
