### ISSUE TITLE
Co usage map navigation with big models

### ISSUE THREAD

**Issue by akevalion** [moosetechnology/MooseIDE#469]
With Nicolas we saw that for big models like this one:
![image](https://user-images.githubusercontent.com/10532890/157407384-c5f6b448-3fe0-41df-8a4d-25574e09912c.png)

This visualization has an interaction when you move the mouse over an inner box, all the boxes with that model will highlight
It is really hard to see selected inner boxes, across the whole visualization.
Then to solve this.
The visualization boxes should adapt to the current width of browser extent
CoUsageMap visualization should allow to the inner boxes be selected with left click, that should allow users check different outer boxes across the visualization, to unselect an inner box, users can click over an outer box or the canvas

**Comment by NicolasAnquetil** [comment]
I would say select with simple right click.
We don't need right click for anything currently (no need to move the inner boxes)

and to unselect, I would right click again on the same inner box (remove the selection), or on another inner box (select another one)

**Comment by akevalion** [comment]
I have created MiCoHighlightManager for highlighting in co usage map
And now each time the browser changes its extent the layout will update with the width of the canvas
