### ISSUE TITLE
Midas model/presenter framework needs to be reviewed ?

### ISSUE THREAD

**Issue by NicolasAnquetil** [moosetechnology/MooseIDE#47]
in MiModelRootBrowser>>initializePresenters we have:
```Smalltalk
initializePresenters
[...]
	modelPresenter
		whenSelectionChangedDo: [ :selected | 
			model selected: selected selectedItem.
			self application globallySelect: selected selectedItem ]
```

I believe the second instruction (`self application ...`) should be in the model, not the `SpecPresenter`.
But this means accessing the `application` from the model which kind of implies all models of all MiBrowsers should have it, whereas Spec places it in the presenter (this is an instance variable of `SpPresenter`).

Having `application` in the model also suggests we need an abstract class of models to generalize this.

**Comment by anneetien** [comment]
The code has been changed and it seems this issue is no more relevant.
