### ISSUE TITLE
propagation FMSlotMultivalueLink

### ISSUE THREAD

**Issue by akevalion** [moosetechnology/MooseIDE#479]
Steps to reproduce it
* open Moose Models browser
* create a model with for example `Morphics-Widget-Windows`
* inspect the moose model
* select all classes
* choose a class with methods
* methods are storage in `FMSlotMultivalueLink`
* try to propagate methods object, with propa
* Propagation methods is not going to work because instances of `FMSlotMultivalueLink` return false to this method `isMooseEntity`

Expected result:
FMSlotMultivalueLink should be propagated

**Comment by NicolasAnquetil** [comment]
or maybe when propagating we just add #asMooseGroup ?
