### ISSUE TITLE
CoUsage browser: handle huge number of children

### ISSUE THREAD

**Issue by NicolasAnquetil** [moosetechnology/MooseIDE#493]
Size of inner boxes depends on number of occurences in the outer box.
But sometimes it is very large:
![image](https://user-images.githubusercontent.com/14889146/158594431-ebdd7595-f343-4c0f-956c-62670de2c45c.png)

- There should be a setting to force a maximum to the value (and consequently also a minimum)
- There should be a setting to use log scale

**Comment by akevalion** [comment]
In these case we can set the scale to sqrt or log

**Comment by NicolasAnquetil** [comment]
yes, witha setting so that the user as the choice.
But I don't like log (or sqrt) very much because it is very difficult to interpret.
So we could also just use a linear scale and set a maximum value (everything above that value will be displayed as the maximum)
And if there is a maximum, it seems logical to also allow a minimum

**Comment by akevalion** [comment]
Here I will show you different pictures of how this looks with diffferent mehods

Current state, width is: (att numberOfUsesOn: met) * 5
<img width="795" alt="image" src="https://user-images.githubusercontent.com/10532890/159048778-8caf1476-1eda-460a-9aa1-e303078c22fd.png">


Using linear with a NSScale,  check scales [scales](https://github.com/ObjectProfile/NumericScales) for more info
```st
NSScale linear
	domain: #(0 10);
	range: #(5 50);
	clamp: true;
	yourself.
```
Enabled clamp will set the maximun size for value.
scale scale: 20"will return 50".
<img width="797" alt="image" src="https://user-images.githubusercontent.com/10532890/159050483-766f737a-65c6-4fa5-ba86-8e59fd47d8e5.png">

With sqrt scale
<img width="797" alt="image" src="https://user-images.githubusercontent.com/10532890/159050055-e4218a2a-fe4a-48c5-ae59-e015a8dc405b.png">


With log scale
<img width="796" alt="image" src="https://user-images.githubusercontent.com/10532890/159049950-9dad3578-3c3a-46a3-bcd7-fc716162e0fe.png">

As you can see there are 6 different values to choose.
- type of scale: linear, pow, sqrt, log
- min value for domain: by default case 0
- max value for domain: 10 but it should be the maximun number of attributes of all current method
- min value for range: 5 pixels
- max value for range: 50 pixels
- clamp: enabled or not

@NicolasAnquetil Do you want to include a setting that can generate an scale from these values?

**Comment by NicolasAnquetil** [comment]
nice work
yes I would like settings with:
- linear or log scales (I think we don't need pow and sqrt)
- domain is 0 to max-of-current-data
- range will always be #(5 50) *i.e.* no settings
- clamp is true by default and can be changed

**Comment by Ducasse** [comment]
super nice

**Comment by akevalion** [comment]
Ok I have added a normalization
<img width="794" alt="image" src="https://user-images.githubusercontent.com/10532890/159694166-c5c4bec0-456e-40d2-98d3-375683e0b8b3.png">

From settings you can change the type of the scale, and the range of the scale used to normalize the inner box width.
<img width="896" alt="image" src="https://user-images.githubusercontent.com/10532890/159694306-7f536b97-6e81-486b-9646-4de67a7edec8.png">
