### ISSUE TITLE
MiCoUsageMapVisualization producer of FamixTag ?

### ISSUE THREAD

**Issue by NicolasAnquetil** [moosetechnology/MooseIDE#504]
(following #503)
Why is MiCoUsageMapVisualization registered as producer of Tag ?

For the "Need work" tag ?
If so, I don't think this is needed, just create the tag (if it does not exist) and don't tell anybody who did it

**Comment by LABSARI** [comment]
It is for the "Need work" tag, yes.
When we create it, we need to notify to other browsers that this tag was created. Especially,  tag browser needs to know when a tag is created outside of it in order to show the tag in its list.

**Comment by akevalion** [comment]
@NicolasAnquetil can you check it and close the issue

**Comment by akevalion** [comment]
Hello, co usage map needs a conflict tag, to use the automatic color feature. If I remove `Need work` should I remove also the automatic color feature?

**Comment by NicolasAnquetil** [comment]
no, keep automatic tagging, but when there is a conflict, you don't do anything

**Comment by akevalion** [comment]
done
