### ISSUE TITLE
Do we need producer/consumer of FamixTagAssociation ?

### ISSUE THREAD

**Issue by NicolasAnquetil** [moosetechnology/MooseIDE#506]
may be just saying that a tag was "edited" would be enough ?

**Comment by akevalion** [comment]
No it is not enough because in co usage map, FamixTagAssociation sets the specific entity with the color.
This helps to interact faster with big visualizations.

If we only use a Tag with update method, this process is going to be slower.

**Comment by akevalion** [comment]
@NicolasAnquetil can we close this issue?
