### ISSUE TITLE
Number of methods using an attribute and not number of accesses

### ISSUE THREAD

**Issue by akevalion** [moosetechnology/MooseIDE#508]
All inner boxes by default should use the number of uses by outer methods

**Comment by akevalion** [comment]
@NicolasAnquetil then for this method
<img width="418" alt="image" src="https://user-images.githubusercontent.com/10532890/159748751-af29e8ee-5756-429e-886d-c6a3f708dff0.png">
The correct size is 6 instead of 2, on this method, right?

**Comment by NicolasAnquetil** [comment]
yes, 6 not 2
and then the size is always the same for a given inner box wherever it appears

**Comment by akevalion** [comment]
Ok I have change it, the attributes size depends on the number of total number. The block settings is still the same

<img width="1294" alt="image" src="https://user-images.githubusercontent.com/10532890/159899649-098b05a6-9e04-4eef-b082-8330f0001a0d.png">

**Comment by akevalion** [comment]
done
