### ISSUE TITLE
Cousage map takes too much time to compute on 200 methods a lot of attributes

### ISSUE THREAD

**Issue by akevalion** [moosetechnology/MooseIDE#509]
You should use a progress bar to show the progress

**Comment by akevalion** [comment]
I have added a progress bar using jobs (class Job)
Currently the job shows the rendering process of the of cousage map, it blocks the main process

**Comment by NicolasAnquetil** [comment]
1- Be careful that the progress bar itself can really slow down the whole execution
2- may be just showing a "busy icon" would be enough ?
@ClotildeToullec did something like that for queries I believe

**Comment by NicolasAnquetil** [comment]
is the same canvas that the one that will display the final result of the visualization ?

did you check how much it's slowing down the execution of the "job" ? (and is it reasonnable?)

**Comment by akevalion** [comment]
These are the differences
- The bar is rendered in a RSCanvas instead of the morph bar.
- This is using a fork, then does not block the main process. But we can do the same withe Job
- after the rendering process the bar will be removed, and all the nodes and shapes created in the process will be displayed.
- There is no benchmark, then I do not know if the current implementation is better or worst than job.
- In co usage map you can selected if you want or not the asynchronous rendering with the method `shouldUseProgressBar`

I will create a benchmark to compare both

**Comment by NicolasAnquetil** [comment]
No, no need of a benchmark
I just wanted to compare the time to render the visualization with the bar and without. Not compare with Job

**Comment by akevalion** [comment]
## Smalltalk example
<img width="765" alt="image" src="https://user-images.githubusercontent.com/10532890/161971705-68166e0e-be5a-44ee-a0f0-934d47ac4182.png">
With 7647 entities(methods) from Morphic-Widget-Windows package

## nckhost_anonime
This is for nckhost_anonime class TypesAnonyme6768 with  1272 methods.
<img width="916" alt="image" src="https://user-images.githubusercontent.com/10532890/161976634-881cd56b-3afd-49a9-8cb7-29cc1da38352.png">

This code shows how to reproduce the chart https://gist.github.com/akevalion/c17b38a75cec35d18cf0f872f471d660

**Comment by akevalion** [comment]
Merged
