### ISSUE TITLE
Settings should be for each instance of co usage map

### ISSUE THREAD

**Issue by akevalion** [moosetechnology/MooseIDE#512]
Except need work tag.

**Comment by akevalion** [comment]
There will be 2 kind of settings, global settings and instance settings based on global settings

**Comment by NicolasAnquetil** [comment]
Nice, can we remove the left "window" ?
Or have it in a separate "settings window" like before ?
Because on 27" screen, we need all the screen space to be able to work on a large class

nicolas

**Comment by akevalion** [comment]
Yes I will put a button close to the line to show it or hide it

**Comment by akevalion** [comment]
Update from today
<img width="897" alt="image" src="https://user-images.githubusercontent.com/10532890/162235160-bea84e30-bf36-47ca-9061-7e89a5a68e52.png">

**Comment by akevalion** [comment]
I have finish the settings browser
<img width="896" alt="image" src="https://user-images.githubusercontent.com/10532890/165120071-cb305cbc-9e60-4e99-8409-3359c8c4bf5e.png">

**Comment by akevalion** [comment]
merged
