### ISSUE TITLE
MiDependencyBrowserModel display action does not accept MooseModels

### ISSUE THREAD

**Issue by NicolasAnquetil** [moosetechnology/MooseIDE#55]
```Smalltalk
MiDependencyBrowserModel>>followAction
	(self accept: toSelect) ifFalse: [ ^ self ].
	(toSelect isOfType: MooseGroup)
		ifTrue: [ self model entities: toSelect ]
		ifFalse: [ self model entities: {toSelect} ].
[...]
```
in `MiDependencyBrowserModel>>accept:` we check that the selection is a collection, but later in `followAction` we check for a `MooseGroup`

MooseModels are `MooseAbstractGroups` so they are treated as a single entity :-(

**Comment by anneetien** [comment]
MiDependencyBrowserModel does not exist anymore in the image
