### ISSUE TITLE
Add "propagate on: aBus" button

### ISSUE THREAD

**Issue by NicolasAnquetil** [moosetechnology/MooseIDE#565]
alternatively to "propagate" button we could have a "propagate on: aBus" button that would propagate once on a bus that the tool does not currently follow

**Comment by NicolasAnquetil** [comment]
see also #564

**Comment by anneetien** [comment]
I don't understand this issue since it is possible to select the buses on the bus list on which to propagate.
@NicolasAnquetil does it still make sence?
