### ISSUE TITLE
Models browser: import button disabled after invalid input in smalltalk importer

### ISSUE THREAD

**Issue by LABSARI** [moosetechnology/MooseIDE#580]
To reproduce, click on import button with no packages selected (see screenshot below). 

<img width="498" alt="image" src="https://user-images.githubusercontent.com/75275113/167375498-af9251f5-78c5-4d58-9030-59f7ed78dafb.png">

**Comment by NicolasAnquetil** [comment]
if you have no packages in your model, you cannot create it, so import should be disabled, no ?

**Comment by ClotildeToullec** [comment]
Yes, the issue is confusing: the problem is that the button does not get enabled again when selecting a package.
It should be:
- Disabled when package list is empty
- Enabled when at least 1 package
- Updating correctly (test!)
