### ISSUE TITLE
Build a browser for a Dependency Structural Matrix (DSM)

### ISSUE THREAD

**Issue by ClotildeToullec** [moosetechnology/MooseIDE#596]
This visualization shows dependencies between entities as a matrix.
Use the Roassal visualization RSDSM2, in package Roassal3-DSM, not loaded in pharo images by default but present in Roassal3 repo: https://github.com/ObjectProfile/Roassal3/tree/master/src/Roassal3-DSM.
This implies baseline management.

**Comment by NicolasAnquetil** [comment]
Milton worked on the DSM to adapt it to Roassal3 and latest Pharo, so now, we "just need" to create the Browser around this roassal visualization
