### ISSUE TITLE
Hierarchical map: incorrect dependencies on Polymath use case

### ISSUE THREAD

**Issue by ClotildeToullec** [moosetechnology/MooseIDE#597]
With Polymath packages, not all dependencies are shown.
![Capture d’écran 2022-05-19 à 11 54 33](https://user-images.githubusercontent.com/39184695/169267120-4f6761e8-35f7-416b-937e-5bcf6a06d629.png)

### To reproduce:
1- Load Polymath: 
``` Smalltalk 
Metacello new
        repository: 'github://PolyMathOrg/PolyMath:v1.0.4';
        baseline: 'PolyMath';
        load
```
2- Import model from pharo (packages starting with 'Math-')
3- Propagated all model packages
4- Hierarchical map showing all links (child query: scope down to classes).

Should be discussed with @olekscode

**Comment by NicolasAnquetil** [comment]
I have the same problem with an argouml model
I am not sure, but when I do "Show all dependencies", there are surprisingly few links appearing (it is not all black with the arrows), so there must be a problem
