### ISSUE TITLE
Color picker is not complete after restarting an image

### ISSUE THREAD

**Issue by ClotildeToullec** [moosetechnology/MooseIDE#602]
To reproduce:
In a Moose 10 image with a model loaded and propagated.
- Open a tag browser and create a tag. Works perfectly:
![Capture d’écran 2022-05-19 à 16 07 34](https://user-images.githubusercontent.com/39184695/169314366-e87f863a-09a0-4d1d-8bb7-5ed1ed2358a1.png)
- Quit pharo (save)
- Restart the image
- Try to create a new tag
![Capture d’écran 2022-05-19 à 16 10 41](https://user-images.githubusercontent.com/39184695/169314655-c16e4385-2516-4d14-9af8-142858fb1dcd.png)
Color picker is missing circles around the chosen color and color samples.

**Comment by NicolasAnquetil** [comment]
I had this same bug, but you went further by identifying the cause of the problem (quitting and restarting the image)

**Comment by LABSARI** [comment]
This issue is fixed through this PR on the Roassal3 repo : https://github.com/ObjectProfile/Roassal3/pull/447
