### ISSUE TITLE
Remove MalTarjan from image

### ISSUE THREAD

**Issue by NicolasAnquetil** [moosetechnology/MooseIDE#623]
Tarjan algorithm is now implemented in Pharo-AI.
We should remove the moose-algo (Mal) implementation

It is used in FamixContainerGroupDependencies, so may be make the change there
Or remove FamixContainerGroupDependencies altogether ?

**Comment by jordanmontt** [comment]
Hello, all the algos were ported and fixed (they were some ones, like Dijkstra that were not working properly). Also, I added new algos. So, if you need, you can use the pharo-ai implementation 

As I put in the mail, if MalTarjan is still present there are two posibilities:
- FamixContainerGroupDependencies uses an old fixed dependency of moose algos where MalTarjan still exists
- Someone just copy the class and put it there (that happened with the dependency analyser)

I suspect that `FamixContainerGroupDependencies` references to an old fixed dependency of moose algos

**Comment by ClotildeToullec** [comment]
I'll investigate.

**Comment by jordanmontt** [comment]
Hello, this issue can be close as it was fixed in https://github.com/moosetechnology/Moose/pull/2479
