### ISSUE TITLE
Better inspector page for MooseGroup

### ISSUE THREAD

**Issue by ClotildeToullec** [moosetechnology/MooseIDE#624]
Now that the default behavior in Model Root browser is to propagate only non-stub entities, clicking inspect opens an inspector on a MooseGroup.
The 'Navigation' tab is only the list of entities sorted by name. We lose the easy navigation from inspecting a model, entities sorted by type mostly.

We should have a nicer Navigation tab for MooseGroups. 
:warning: We do not want 'All classes' to be the only item when inspecting a class group, so this should be only for non-specialized groups

**Comment by LABSARI** [comment]
Inspecting a model in model root bowser with only non stub entities is corrected. We don't need to adapt MooseGroup to it.
