### ISSUE TITLE
bug in ModelBrowser settings

### ISSUE THREAD

**Issue by NicolasAnquetil** [moosetechnology/MooseIDE#642]
![image](https://user-images.githubusercontent.com/14889146/171866408-4605b899-f1b8-4644-9463-17dc38346d01.png)

**Comment by NicolasAnquetil** [comment]
Same error occurs with other tools.
The ownerTool instance variable is not set

- settings should be more standardized with methods in MiAbstractBrowser
- settings should be tested

**Comment by ClotildeToullec** [comment]
I find it weird that settings are a presenter.

Shouldn't we have a `SettingsPresenter`and some *settings* in a more Object thinking?
Settings would be instance variables of the Browser or its model.

The settings browser widgets would have the responsibility to change settings **on user action** --> tests.
Then no reference to the settings presenter (which may be closed) when manipulating settings from the Browser or its model. --> tests independent of presenters.

--> No ifTrue:ifFalse: based on the state of a checkbox like in ModelRootBrowser (please)

**Comment by ClotildeToullec** [comment]
That's probably what you mean in #643 Nicolas
