### ISSUE TITLE
Clicking on Add Bus in a Brand New Image and Moose IDE Overview Throws Exception

### ISSUE THREAD

**Issue by yann-gael** [moosetechnology/MooseIDE#654]
Step to reproduce
1. Download the Moose image available in https://rmod-files.lille.inria.fr/?dir=Moose/ETS
2. Run the image in Pharo 10
3. Click on Moose > Moose IDE Overview
4. A window opens
5. Click on "+ Add Bus"

The exception is:

MiOverviewBrowser(Object)>>doesNotUnderstand: #buses
MiBusesPopup>>initializePresenters
MiBusesPopup(SpPresenter)>>initializePrivateHooks
MiBusesPopup(SpPresenter)>>initialize
MiBusesPopup class(SpPresenter class)>>newApplication:model:
MiBusesPopup class(SpPresenter class)>>on:
MiOverviewBrowser>>openBusEditor
[ self openBusEditor ] in MiOverviewBrowser>>initializeToolbar in Block: [ self openBusEditor ]
SpButtonPresenter>>performAction
SpMorphicButtonAdapter>>action
PluggableButtonMorph>>performAction:
[:m |
		(m containsPoint: evt cursorPoint) ifTrue: [m enabled ifTrue: [ m performAction: evt ]]] in PluggableButtonMorph>>mouseUp: in Block: [:m |...
Array(SequenceableCollection)>>do:
PluggableButtonMorph>>mouseUp:
PluggableButtonMorph(Morph)>>handleMouseUp:
MouseButtonEvent>>sentTo:
PluggableButtonMorph(Morph)>>handleEvent:
PluggableButtonMorph(Morph)>>handleFocusEvent:
[
		result := focusHolder handleFocusEvent: transformedEvent.
	] in HandMorph>>sendFocusEvent:to:clear: in Block: [...
FullBlockClosure(BlockClosure)>>on:do:
WorldMorph>>becomeActiveDuring:
HandMorph>>sendFocusEvent:to:clear:
HandMorph>>sendEvent:focus:clear:
HandMorph>>sendMouseEvent:
HandMorph>>handleEvent:
[
		(morphicWorld activeHand isNotNil and: [ anEvent hand isNotNil ]) ifTrue: [
			morphicWorld activeHand handleEvent: anEvent
		]
	] in OSWindowMorphicEventHandler>>dispatchMorphicEvent: in Block: [...
WorldState>>runStepMethodsIn:
WorldMorph>>runStepMethods
WorldState>>doOneCycleFor:
WorldMorph>>doOneCycleNow

**Comment by ClotildeToullec** [comment]
Hm, it seems this button is not really necessary or not in the right place.

I think the intent was to be able to add a bus that would then be available to all browsers in the application.
If this feature is needed, the button should probably be local to the 'Buses' tab, below (above?) the list of currently existing buses.

What do you think?

**Comment by NicolasAnquetil** [comment]
Yes, I agree with your analysis

And we should also remove the check box in the list that opens.
The problem seems to come from the use of MiBusesPopup which incidentally has this comment:
"_In MooseIDE Overview, I show all the existing buses --> I only show the buses names, no need for checkboxes._"
:-)

**Comment by akevalion** [comment]
From pharo launcher I have downloaded the moose image 
and I do not find the error
<img width="966" alt="image" src="https://user-images.githubusercontent.com/10532890/175543848-d6bcbc5f-350d-408a-810a-b4c311776b98.png">

But If I enter a new bus I got this error
<img width="969" alt="image" src="https://user-images.githubusercontent.com/10532890/175544008-e5106661-dc81-4a66-8316-e5b01e7ff231.png">
