### ISSUE TITLE
QueriesBrowser: Scope query should allow to recursively look for result

### ISSUE THREAD

**Issue by LABSARI** [moosetechnology/MooseIDE#659]
First step is to add a recursive option in FQScopeQuery class (MQScopeQuery already has it). For now we can not construct a recursive scope query using Famix queries. Don't forget to update the FQScopeQuery>>storeOn: with that recursive option, in order to print the query (used in "Current query code" tab of queries browser).

Second step is to add a graphical option for it in the queries browser (maybe a checkbox?).

**Comment by NicolasAnquetil** [comment]
What do you mean by "recursive" ?

**Comment by anneetien** [comment]
Il fact, if you want to get all the packages that do not belong to a ‘client’ package whatever the depth. It is not possible to do it with the QueryBrowser neither with MooseQuery.

Anne

**Comment by NicolasAnquetil** [comment]
OK, makes sense
Yes, we would need an option to control that

But I wonder if we could avoid having "2 DSLs" (MooseQuery and FamixQuery) which I don't see as a good thing
