### ISSUE TITLE
Improve the speed of all MooseIDE tools

### ISSUE THREAD

**Issue by jecisc** [moosetechnology/MooseIDE#67]
Midas needs to be tested on big models. 

I am currently trying some things on a middle size model and some interfaces takes a really long time to show.

It's probably related to the interfaces because equivalent tools in the Siemens toolkit are much faster.

**Comment by jordanmontt** [comment]
There are performance issues in all MooseIDE tools

**Comment by anneetien** [comment]
without more details and after 3 years, I propose to close the issue.
Improvements have been done during the years anyway.

**Comment by jecisc** [comment]
I did a lot of work on that already. 

There are still space for improvements but it is already way better than in the past
