### ISSUE TITLE
Truncation of information (...) at top of inspector

### ISSUE THREAD

**Issue by fuhrmanator** [moosetechnology/MooseIDE#674]
Selected items have their info truncated with "..." in the browser, despite space to show it. 

In the following example, we only see `a FamixTypeScriptIndexedFil...` but there is plenty of space to show more information as shown by the red arrow:

![image](https://user-images.githubusercontent.com/7606540/175552707-b0fd052f-96be-419f-ba97-2ffd6ceb44a5.png)

This is also a problem in the individual inspector:

![image](https://user-images.githubusercontent.com/7606540/175553247-a17f6ded-6b61-4855-9f38-22b958f75861.png)

**Comment by LABSARI** [comment]
It is related to the Pharo inspector, not a Moose business.
