### ISSUE TITLE
Refresh button after `install` of a model doesn't refresh the Models browser window

### ISSUE THREAD

**Issue by fuhrmanator** [moosetechnology/MooseIDE#675]
When testing by hand, I load my TypeScript models with a script because it's faster:

```st
'../../../GitHub/FamixTypeScriptImporter/emojiopoly.json' asFileReference 
	readStreamDo: [ :stream | model := FamixTypeScriptModel new
	importFromJSONStream: stream. 
	model name: 'emojiopoloy3'. 
	model install ].
```

However, the Models browser doesn't show the `install`ed model until I close it and re-open it. I'm not sure if it's possible to refresh it on the `install` method, or is there a way I can force it in my script?

**Comment by badetitou** [comment]
The script is part of Moose where the browser is part of MooseIDE. 
It is normal that there is no link from Moose to MooseIDE ( elsewhere. There will be cyclic dependency )

The good way would be to not use a script but to import using the MooseIDE. 

Another solution is to perform something like : MooseBrowser allInstances refreshButton click (I am not in front of the code. But it should be possible )

**Comment by fuhrmanator** [comment]
> MooseBrowser allInstances refreshButton click

I didn't realize there was a refresh button. But now that I tried it, I see that it does not work.

**Comment by fuhrmanator** [comment]
I'm in Windows 10, if it makes any difference. Here's a video:

![Pharo_SaZdpWErgn](https://user-images.githubusercontent.com/7606540/175557397-11b5ae50-b66e-4c85-a03a-dec78cd95454.gif)
