### ISSUE TITLE
Display current computed critics

### ISSUE THREAD

**Issue by badetitou** [moosetechnology/MooseIDE#700]
It would be great to have information about the currently computed rules or critics in the Critic browser

![image](https://user-images.githubusercontent.com/6225039/187693710-fef70164-3648-4fe7-b46e-98564b7dab21.png)

In the above example, I have liked on run, but I have no way to determine the current step of the process.
I'm thinking about something like in Dr.TEST

![image](https://user-images.githubusercontent.com/6225039/187694061-6ccb2dbb-61f8-4f8e-8798-58f8d3c72100.png)

**Comment by Gabriel-Darbord** [comment]
Sadly the PR #746 is still stuck :/
