### ISSUE TITLE
MiListSelector is a re-implementaion of SpChooserPresenter

### ISSUE THREAD

**Issue by jordanmontt** [moosetechnology/MooseIDE#701]
The presenter `MiListSelector`:

<img width="499" alt="Capture d’écran 2022-08-31 à 21 23 11" src="https://user-images.githubusercontent.com/33934979/187764886-48d4a969-5f7b-4002-b048-de32658a37d5.png">

Is actually a re-implementation of an already existing class of Spec `SpChooserPresenter`

<img width="399" alt="Capture d’écran 2022-08-31 à 21 23 50" src="https://user-images.githubusercontent.com/33934979/187764989-722247a5-5d3a-417b-b5de-b6cac5284974.png">

I think that we should only use the default one provided by spec. Also we could send a PR to Spec if needed (for example if we want ot improve `SpChooserPresenter`)

@anneetien

**Comment by Ducasse** [comment]
+1
