### ISSUE TITLE
add a generic #miPropagate method in the system

### ISSUE THREAD

**Issue by NicolasAnquetil** [moosetechnology/MooseIDE#733]
Put a method on Object that would allow to propagate programmatically any object

for example:
```Smalltalk
(aModel allWithType: #FamixPackage) miPropagate
```

And it would propagate the result (as a MooseCollection) on the default bus

**Comment by badetitou** [comment]
I though we did not want to propagate anything that is not a MooseEntity (or something like this)

**Comment by NicolasAnquetil** [comment]
Right, we don't want to propagate non MooseEntity, but I think the tools check that by themselves so there should not be any problem in doing it.

And that way, when you know what you are doing, you have the option.

Maybe instead of putting on Object, we put it on Collection and we do a #asMooseCollection
And may be we can even check there to reject non-MooseEntity ...

It is just that doing everything in the QueryBrowser is so difficult and it is easier to program it, but then it is not easy to bring back the result in MooseIDE: `MiInspectofBrowser inspect: <the-collection> asMooseGroup` + do the inspect in the browser
