### ISSUE TITLE
In Architectural Map, entities should not be ordered alphabetically...

### ISSUE THREAD

**Issue by anneetien** [moosetechnology/MooseIDE#738]
... but according to their parent for example (and a bit like in distribution map, the parent with the most children should be first.

**Comment by NicolasAnquetil** [comment]
Not sure about this one. 
The visualization should group entities in their parent if the parent is preset.
But ordering entities according to the parent if this one is not visible may be unclear.
The ordering needs to be understandable so that user can rely on it to find things

**Comment by LABSARI** [comment]
Entities are not ordered at all. We will order alphabetically.
