### ISSUE TITLE
should the logger have separate windows for each bus?

### ISSUE THREAD

**Issue by NicolasAnquetil** [moosetechnology/MooseIDE#77]
I would have had only one window with all  "events" in it.
May be with an indication on the bus from which they come (2 columns display)

That allows to keep the timeline of the events

**Comment by jordanmontt** [comment]
@NicolasAnquetil 
![image](https://user-images.githubusercontent.com/33934979/120341801-b9c69d00-c2e6-11eb-82fc-102115aaa6c2.png)
maybe we can use a notebook instead of a list? Is that what you are talking about?

**Comment by jordanmontt** [comment]
That could fix #112 too

**Comment by NicolasAnquetil** [comment]
Not sure because I cannot understand myself ! :-)
But I think what I was proposing was that all entries appear in the same pane (not separated like in your example, or with tabs (SPNotebook)).
But with two rows: a small one on the left with the name of the bus and a large one on the right with the entry :
![Screenshot from 2021-06-01 18-48-43](https://user-images.githubusercontent.com/14889146/120363325-4df72b00-c30c-11eb-81bf-b41d51774009.png)

And maybe a timestamp too in the left row

**Comment by anneetien** [comment]
Is this issue still relevant?

**Comment by anneetien** [comment]
There is the MiBusLogger that should answer this issue. If it is not the case, please reopen this issue.
