### ISSUE TITLE
Drag&Drop should not load file *automatically*

### ISSUE THREAD

**Issue by NicolasAnquetil** [moosetechnology/MooseIDE#782]
Currently if a suitable meta-model is found when dropping an mse or json file to moose, this file is automatically loaded.

It seems better to leave the load file window open so that the user can make changes to the parameters (another also compatible meta-model, model name, root folder)

**Comment by badetitou** [comment]
I agree. It would be better to have a window with potential parameters

**Comment by lsafina** [comment]
fixed in the 785 branch
