### ISSUE TITLE
[CRITIC BROWSER] Ability to move rules from one context to another

### ISSUE THREAD

**Issue by Flooze-IT** [moosetechnology/MooseIDE#827]
Hi,
I am a new user of the Moose IDE. I use Moose critric.

**Use case:**

During my rules creation, i create a context A and i define rules in, i create a context B and i define rules in. 

But I realized that i want to wrap this two precedent context in a parent (like in picture below)

![image](https://user-images.githubusercontent.com/83304595/230587726-d422bf24-2014-4bd3-9e25-f12edad4508c.png)

I think, we can imagine that the user can drag a context inside another or duplicate a rule inside another context (like copy/paste to destination)

Good luck ;)

**Comment by ClotildeToullec** [comment]
Drag & drop is a bit complex with this widget. We added a menu item to move a component to another context.
It is not possible to move the root context. It is also not possible to move a context to its children directly.
Don't hesitate to give us feedback!
