### ISSUE TITLE
FamixJavaClass and FamixJavaInterface should be on the same scope

### ISSUE THREAD

**Issue by thomasWattebled** [moosetechnology/MooseIDE#834]
if I take a method from an interface and do "atScope: FamixJavaClass".
I want the interface but it returns nothing

**Comment by NicolasAnquetil** [comment]
yes, I believe JavaInterface and JavaClass should be at the same scope
On the other hand it is may seem strange to say `atScope: FamixJavaClass` and expect an interface.
So may be we need another scope marker ?

Anyway, for now I think  `atScope: FamixJavaClass`  should return Interfaces

**Comment by badetitou** [comment]
Not sure we want to be able to do that.
We can maybe use something like
`atScope: FamixTType` ? 
Or `atAnyScope: { FamixJavaClass . FamixJavaInterface }`

The other option is to declare famix java interface as kind of famixJavaClass or the other way around, but I'm not sure we want that

**Comment by NicolasAnquetil** [comment]
Right.
Tested by @thomasWattebled and both solutions work so closing the issue
