### ISSUE TITLE
Various undefined methods appearing in Moose11 source code

### ISSUE THREAD

**Issue by NicolasAnquetil** [moosetechnology/MooseIDE#847]
Example with `MiArchitecturalMapSettings >> #fillModelWithCurrentSettings` : 
![Screenshot from 2023-05-16 10-33-37](https://github.com/moosetechnology/MooseIDE/assets/14889146/8d33e714-6bb3-4203-80c5-16b941e323bb)

**Comment by thomasWattebled** [comment]
#851
