### ISSUE TITLE
Entity with children cannot be expanded

### ISSUE THREAD

**Issue by nkinesis** [moosetechnology/MooseIDE#882]
Some entities with children cannot be expanded in the Architectural Map.

Steps to reproduce the issue:
It does not happen consistently so it might be hard to reproduce, but you can try loading [this image](https://drive.google.com/drive/folders/1Md7BSKApDoPxvrNWCLmSMOVkZ9mYUhuI?usp=sharing&authuser=0) and following these steps:

Go to the Architectural Map window which is open.
Under the "Audio" tag, you should find the folders "alsa" and "alsamidi". While both have children, only "alsa" can be expanded by right-clicking in and then selecting "expand".
Expected behaviour: both "alsa" and "alsamidi" should be expandable. By inspecting them it is possible to see that the "children" attribute exists for these entities, therefore children should be visible in the visualisation as well.

![image](https://github.com/moosetechnology/MooseIDE/assets/8628634/c47450d1-b146-4a7a-8fa1-63b90e18a9c1)

**Comment by NicolasAnquetil** [comment]
Strange, bothe entities answer correctly to the  `#children` message (give a non-empty collection.

Expandable entities have a square after their name, none expandable ones don't
I don't remember what the square means ...
![image](https://github.com/moosetechnology/MooseIDE/assets/14889146/f778049a-69c8-435f-9ddb-1a103baf9822)

**Comment by LABSARI** [comment]
Children are already present on the map. Since an entity appears only once on the architectural map, it is not added in **alsamidi**. I think this should be an option of the architectural map. Either we duplicate entities or we force the map to respect the hierarchy. The current behaviour is bad because if **alsamidi** was computed before its children, children would have been  inside **alsamidi**.

**Comment by LABSARI** [comment]
> Strange, bothe entities answer correctly to the `#children` message (give a non-empty collection.
> 
> Expandable entities have a square after their name, none expandable ones don't I don't remember what the square means ... ![image](https://user-images.githubusercontent.com/14889146/262281345-f778049a-69c8-435f-9ddb-1a103baf9822.png)

The square means that there is a child in that entity that has the yellow tag.
