### ISSUE TITLE
Green background highlight for nodes hides the name

### ISSUE THREAD

**Issue by NicolasAnquetil** [moosetechnology/MooseIDE#900]
For example, in ArchitecturalMap when on a node, its clients and providers are highlighted in green.
But then, their name is no longer readable
![image](https://github.com/moosetechnology/MooseIDE/assets/14889146/64a3ecf3-df4b-4e6b-92e4-7a1a7a3b2d2d)

**Comment by LABSARI** [comment]
This was fixed in Roassal.
