### ISSUE TITLE
Default text style for MooseIDE visualization is too light

### ISSUE THREAD

**Issue by NicolasAnquetil** [moosetechnology/MooseIDE#902]
By default nodes are light grey with text a bit darker grey. It is not visible enough, text need to be darker yet
![image](https://github.com/moosetechnology/MooseIDE/assets/14889146/a88a32a7-6871-4c64-895d-e4ccaea311bc)

**Comment by badetitou** [comment]
Maybe we can base the color of text on system UI theme?

**Comment by Gabriel-Darbord** [comment]
Cannot reproduce, @LABSARI says it's already based on the theme.
![image](https://github.com/moosetechnology/MooseIDE/assets/78592838/d9fee9fb-6261-439c-be52-e8cf677dd417)
