### ISSUE TITLE
How to create a Manual Query

### ISSUE THREAD

**Issue by badetitou** [moosetechnology/MooseIDE#913]
I tried to create a manual query
![image](https://github.com/moosetechnology/MooseIDE/assets/6225039/ddd37362-71c5-481e-a366-93235a798591)

But it is unclear of what is the format or the existing variables?

**Comment by LABSARI** [comment]
You have to give it a Famix query.
```Smalltalk
FQCollectScriptQuery script: [ :el |  el children ]
```

**Comment by badetitou** [comment]
Maybe during the spring you can change so that the textfield is precompleted?

**Comment by NicolasAnquetil** [comment]
yes, definitely needs improvement
