### ISSUE TITLE
System Complexity: allow user to move entities

### ISSUE THREAD

**Issue by ClotildeToullec** [moosetechnology/MooseIDE#928]

**Comment by ClotildeToullec** [comment]
Make shapes draggable

**Comment by LABSARI** [comment]
The problem is that Clotilde wants to be able to move a class when it is expanded because when expanded the layout can be weird.
It will relayout when a shape is expanded.

**Comment by LABSARI** [comment]
Yes I did.
Do you think it is useful to move nodes on that visualization?

**Comment by NicolasAnquetil** [comment]
as soon as you can expand, you may need to manually move the nodes.
The point is not loosing what the users do if they do move the nodes
