### ISSUE TITLE
Architectural Map - Tag cannot be expanded

### ISSUE THREAD

**Issue by ISayarLu** [moosetechnology/MooseIDE#938]
When a tag is in another tag (what is not easy to do), it is not possible to expand the contained tag.

**Comment by alesshosry** [comment]
@ISayarLu Can you please elaborate more ? Screenshot ...

**Comment by ISayarLu** [comment]
We propagate tags in a map but we cannot expand to see the children (see the right side of the screenshot)  
<img width="1059" alt="Screenshot 2023-11-24 at 10 52 41" src="https://github.com/moosetechnology/MooseIDE/assets/61229307/30a7c543-4cdc-4673-b267-9bed8c5ffd4e">

**Comment by IkiAde** [comment]
It is now possible.
