### ISSUE TITLE
Architectural Map - Containers should have borders

### ISSUE THREAD

**Issue by nkinesis** [moosetechnology/MooseIDE#942]
I'm using tags to group several files and folders in a FamixCPP model. However, the background color of the folder is the same as the background color of the tag, making it hard to see where one thing ends and the other begins. My suggestion: adding a more contrasting color or borders.

![image](https://github.com/moosetechnology/MooseIDE/assets/8628634/506927ec-960e-4db3-bf1a-f4c85fcf4c02)

**Comment by anneetien** [comment]
I remember we did that with Soufyane during a Moose Dojo I guess.
On which version of Moose are you?

Anne

**Comment by nkinesis** [comment]
You are correct, it was resolved in #892.
