### ISSUE TITLE
Propagate freezes the image for few seconds

### ISSUE THREAD

**Issue by LABSARI** [moosetechnology/MooseIDE#954]
With a big model loaded in the image, the propagation (from any browser) freezes the image for few seconds, even when no other browser is open.

**Comment by LABSARI** [comment]
This problem occurs only when a Models browser is open.

**Comment by NicolasAnquetil** [comment]
may be linked to the setting "Filter out stub" (propagation needs to browse through all entities to reject the stubs) ?

**Comment by jecisc** [comment]
This is indeed the filtering of stubs that takes time. I already sped up some things but it's hard to speed thing even more I think.. Should we keep this issue?
