### ISSUE TITLE
MoosequeryBrowser: clearQueries does not reset bottom panel

### ISSUE THREAD

**Issue by NicolasAnquetil** [moosetechnology/MooseIDE#963]
Open a QueryBrowser on some model : bottom panel shows all entities in the model
Do a query or two : bottom panel shows result of query
click on button "clear queries" : all queries are removed from top panel but bottom panel is empty

One would expect it to return to the initial state: showing all entities in the model

**Comment by ClotildeToullec** [comment]
Same as #1025 
Fixed in #1030
