### ISSUE TITLE
DistributionMap setting: list of tags should be a list with check boxes

### ISSUE THREAD

**Issue by NicolasAnquetil** [moosetechnology/MooseIDE#965]
Currently there are two windows:
- first when one click on "change" button in setting window, a list of selected tags appears. It is initially empty
- then when one click on "+" button on this first list, another window appears to select the tags to add.

The first list should be a list of all available tags with check buttons (ex: SpFilteringSelectableListPresenter) and the user can select the wanted tags  directly from there

**Comment by uNouss** [comment]
#1002 Fix
